// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
)

// Defines values for AddShopBadRequestErrorBodyType.
const (
	AddShopBadRequestErrorBodyTypeInvalidRequest AddShopBadRequestErrorBodyType = "invalid_request"
)

// Defines values for AddShopField.
const (
	AddShopFieldAddress       AddShopField = "address"
	AddShopFieldCategory      AddShopField = "category"
	AddShopFieldClosed        AddShopField = "closed"
	AddShopFieldGooglePlaceId AddShopField = "googlePlaceId"
	AddShopFieldLat           AddShopField = "lat"
	AddShopFieldLng           AddShopField = "lng"
	AddShopFieldName          AddShopField = "name"
	AddShopFieldPostalCode    AddShopField = "postalCode"
	AddShopFieldTagIds        AddShopField = "tagIds"
)

// Defines values for AuthenticationRequiredErrorBodyType.
const (
	AuthenticationRequired AuthenticationRequiredErrorBodyType = "authentication_required"
)

// Defines values for CategorySlug.
const (
	Ramen CategorySlug = "ramen"
	Udon  CategorySlug = "udon"
)

// Defines values for FieldErrorType.
const (
	Duplicate     FieldErrorType = "duplicate"
	InvalidFormat FieldErrorType = "invalid_format"
	OutOfRange    FieldErrorType = "out_of_range"
	Required      FieldErrorType = "required"
	TooLong       FieldErrorType = "too_long"
	Unknown       FieldErrorType = "unknown"
)

// Defines values for GoogleAuthBadRequestErrorBodyType.
const (
	GoogleAuthBadRequestErrorBodyTypeGoogleAuthFailed GoogleAuthBadRequestErrorBodyType = "google_auth_failed"
	GoogleAuthBadRequestErrorBodyTypeInvalidRequest   GoogleAuthBadRequestErrorBodyType = "invalid_request"
)

// Defines values for GoogleAuthField.
const (
	Credential GoogleAuthField = "credential"
)

// Defines values for InternalErrorBodyType.
const (
	InternalError InternalErrorBodyType = "internal_error"
)

// Defines values for InvalidRequestErrorBodyType.
const (
	InvalidRequestErrorBodyTypeInvalidRequest InvalidRequestErrorBodyType = "invalid_request"
)

// Defines values for PermissionDeniedErrorBodyType.
const (
	PermissionDenied PermissionDeniedErrorBodyType = "permission_denied"
)

// Defines values for SessionCreationFailedErrorBodyType.
const (
	SessionCreationFailed SessionCreationFailedErrorBodyType = "session_creation_failed"
)

// Defines values for TagBadRequestErrorBodyType.
const (
	TagBadRequestErrorBodyTypeInvalidRequest TagBadRequestErrorBodyType = "invalid_request"
)

// Defines values for TagField.
const (
	TagFieldCategory  TagField = "category"
	TagFieldColor     TagField = "color"
	TagFieldLabel     TagField = "label"
	TagFieldSlug      TagField = "slug"
	TagFieldSortOrder TagField = "sortOrder"
)

// Defines values for UpdateShopBadRequestErrorBodyType.
const (
	InvalidRequest UpdateShopBadRequestErrorBodyType = "invalid_request"
)

// Defines values for UpdateShopField.
const (
	Address       UpdateShopField = "address"
	Category      UpdateShopField = "category"
	Closed        UpdateShopField = "closed"
	Eaten         UpdateShopField = "eaten"
	Favorite      UpdateShopField = "favorite"
	GooglePlaceId UpdateShopField = "googlePlaceId"
	Lat           UpdateShopField = "lat"
	Lng           UpdateShopField = "lng"
	Name          UpdateShopField = "name"
	PostalCode    UpdateShopField = "postalCode"
	Rate          UpdateShopField = "rate"
	TagIds        UpdateShopField = "tagIds"
)

// AddShopBadRequestErrorBody defines model for AddShopBadRequestErrorBody.
type AddShopBadRequestErrorBody struct {
	FieldErrors *[]AddShopFieldError           `json:"fieldErrors,omitempty"`
	Message     *string                        `json:"message,omitempty"`
	Type        AddShopBadRequestErrorBodyType `json:"type"`
}

// AddShopBadRequestErrorBodyType defines model for AddShopBadRequestErrorBody.Type.
type AddShopBadRequestErrorBodyType string

// AddShopField defines model for AddShopField.
type AddShopField string

// AddShopFieldError defines model for AddShopFieldError.
type AddShopFieldError struct {
	Field   AddShopField   `json:"field"`
	Message *string        `json:"message,omitempty"`
	Type    FieldErrorType `json:"type"`
}

// AddShopRequest defines model for AddShopRequest.
type AddShopRequest struct {
	Address       string       `json:"address"`
	Category      CategorySlug `json:"category"`
	Closed        bool         `json:"closed"`
	GooglePlaceId string       `json:"googlePlaceId"`
	Lat           float64      `json:"lat"`
	Lng           float64      `json:"lng"`
	Name          string       `json:"name"`
	PostalCode    string       `json:"postalCode"`
	TagIds        []Uuid       `json:"tagIds"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	User User `json:"user"`
}

// AuthenticationRequiredErrorBody defines model for AuthenticationRequiredErrorBody.
type AuthenticationRequiredErrorBody struct {
	Message *string                             `json:"message,omitempty"`
	Type    AuthenticationRequiredErrorBodyType `json:"type"`
}

// AuthenticationRequiredErrorBodyType defines model for AuthenticationRequiredErrorBody.Type.
type AuthenticationRequiredErrorBodyType string

// CategorySlug defines model for CategorySlug.
type CategorySlug string

// FieldErrorType defines model for FieldErrorType.
type FieldErrorType string

// GoogleAuthBadRequestErrorBody defines model for GoogleAuthBadRequestErrorBody.
type GoogleAuthBadRequestErrorBody struct {
	FieldErrors *[]GoogleAuthFieldError           `json:"fieldErrors,omitempty"`
	Message     *string                           `json:"message,omitempty"`
	Type        GoogleAuthBadRequestErrorBodyType `json:"type"`
}

// GoogleAuthBadRequestErrorBodyType defines model for GoogleAuthBadRequestErrorBody.Type.
type GoogleAuthBadRequestErrorBodyType string

// GoogleAuthField defines model for GoogleAuthField.
type GoogleAuthField string

// GoogleAuthFieldError defines model for GoogleAuthFieldError.
type GoogleAuthFieldError struct {
	Field   GoogleAuthField `json:"field"`
	Message *string         `json:"message,omitempty"`
	Type    FieldErrorType  `json:"type"`
}

// GoogleAuthRequest defines model for GoogleAuthRequest.
type GoogleAuthRequest struct {
	Credential string `json:"credential"`
}

// InternalErrorBody defines model for InternalErrorBody.
type InternalErrorBody struct {
	Message *string               `json:"message,omitempty"`
	Type    InternalErrorBodyType `json:"type"`
}

// InternalErrorBodyType defines model for InternalErrorBody.Type.
type InternalErrorBodyType string

// InvalidRequestErrorBody defines model for InvalidRequestErrorBody.
type InvalidRequestErrorBody struct {
	Message *string                     `json:"message,omitempty"`
	Type    InvalidRequestErrorBodyType `json:"type"`
}

// InvalidRequestErrorBodyType defines model for InvalidRequestErrorBody.Type.
type InvalidRequestErrorBodyType string

// PermissionDeniedErrorBody defines model for PermissionDeniedErrorBody.
type PermissionDeniedErrorBody struct {
	Message *string                       `json:"message,omitempty"`
	Type    PermissionDeniedErrorBodyType `json:"type"`
}

// PermissionDeniedErrorBodyType defines model for PermissionDeniedErrorBody.Type.
type PermissionDeniedErrorBodyType string

// SaveTagsRequest defines model for SaveTagsRequest.
type SaveTagsRequest struct {
	Tags []TagInput `json:"tags"`
}

// SessionCreationFailedErrorBody defines model for SessionCreationFailedErrorBody.
type SessionCreationFailedErrorBody struct {
	Message *string                            `json:"message,omitempty"`
	Type    SessionCreationFailedErrorBodyType `json:"type"`
}

// SessionCreationFailedErrorBodyType defines model for SessionCreationFailedErrorBody.Type.
type SessionCreationFailedErrorBodyType string

// Shop defines model for Shop.
type Shop struct {
	Address       string       `json:"address"`
	Category      CategorySlug `json:"category"`
	Closed        bool         `json:"closed"`
	Eaten         bool         `json:"eaten"`
	Favorite      bool         `json:"favorite"`
	GooglePlaceId string       `json:"googlePlaceId"`

	// Id UUID serialized as a string.
	Id         Uuid    `json:"id"`
	Lat        float64 `json:"lat"`
	Lng        float64 `json:"lng"`
	Name       string  `json:"name"`
	PostalCode string  `json:"postalCode"`
	Rate       float64 `json:"rate"`
	Tags       []Tag   `json:"tags"`
}

// ShopsResponse defines model for ShopsResponse.
type ShopsResponse struct {
	Shops []Shop `json:"shops"`
}

// Tag defines model for Tag.
type Tag struct {
	Category *CategorySlug `json:"category,omitempty"`
	Color    string        `json:"color"`

	// Id UUID serialized as a string.
	Id        Uuid   `json:"id"`
	Label     string `json:"label"`
	Slug      string `json:"slug"`
	SortOrder int32  `json:"sortOrder"`
}

// TagBadRequestErrorBody defines model for TagBadRequestErrorBody.
type TagBadRequestErrorBody struct {
	FieldErrors *[]TagFieldError           `json:"fieldErrors,omitempty"`
	Message     *string                    `json:"message,omitempty"`
	Type        TagBadRequestErrorBodyType `json:"type"`
}

// TagBadRequestErrorBodyType defines model for TagBadRequestErrorBody.Type.
type TagBadRequestErrorBodyType string

// TagField defines model for TagField.
type TagField string

// TagFieldError defines model for TagFieldError.
type TagFieldError struct {
	Field   TagField       `json:"field"`
	Message *string        `json:"message,omitempty"`
	Type    FieldErrorType `json:"type"`
}

// TagInput defines model for TagInput.
type TagInput struct {
	Category *CategorySlug `json:"category,omitempty"`
	Color    string        `json:"color"`

	// Id UUID serialized as a string.
	Id        *Uuid  `json:"id,omitempty"`
	Label     string `json:"label"`
	Slug      string `json:"slug"`
	SortOrder int32  `json:"sortOrder"`
}

// TagsResponse defines model for TagsResponse.
type TagsResponse struct {
	Tags []Tag `json:"tags"`
}

// UpdateShopBadRequestErrorBody defines model for UpdateShopBadRequestErrorBody.
type UpdateShopBadRequestErrorBody struct {
	FieldErrors *[]UpdateShopFieldError           `json:"fieldErrors,omitempty"`
	Message     *string                           `json:"message,omitempty"`
	Type        UpdateShopBadRequestErrorBodyType `json:"type"`
}

// UpdateShopBadRequestErrorBodyType defines model for UpdateShopBadRequestErrorBody.Type.
type UpdateShopBadRequestErrorBodyType string

// UpdateShopField defines model for UpdateShopField.
type UpdateShopField string

// UpdateShopFieldError defines model for UpdateShopFieldError.
type UpdateShopFieldError struct {
	Field   UpdateShopField `json:"field"`
	Message *string         `json:"message,omitempty"`
	Type    FieldErrorType  `json:"type"`
}

// UpdateShopRequest defines model for UpdateShopRequest.
type UpdateShopRequest struct {
	Address       string       `json:"address"`
	Category      CategorySlug `json:"category"`
	Closed        bool         `json:"closed"`
	Eaten         bool         `json:"eaten"`
	Favorite      bool         `json:"favorite"`
	GooglePlaceId string       `json:"googlePlaceId"`
	Lat           float64      `json:"lat"`
	Lng           float64      `json:"lng"`
	Name          string       `json:"name"`
	PostalCode    string       `json:"postalCode"`
	Rate          float64      `json:"rate"`
	TagIds        []Uuid       `json:"tagIds"`
}

// User defines model for User.
type User struct {
	Email string `json:"email"`

	// Id UUID serialized as a string.
	Id      Uuid `json:"id"`
	IsAdmin bool `json:"isAdmin"`
}

// Uuid UUID serialized as a string.
type Uuid = string

// GoogleAuthJSONRequestBody defines body for GoogleAuth for application/json ContentType.
type GoogleAuthJSONRequestBody = GoogleAuthRequest

// AddShopJSONRequestBody defines body for AddShop for application/json ContentType.
type AddShopJSONRequestBody = AddShopRequest

// UpdateShopJSONRequestBody defines body for UpdateShop for application/json ContentType.
type UpdateShopJSONRequestBody = UpdateShopRequest

// SaveTagsJSONRequestBody defines body for SaveTags for application/json ContentType.
type SaveTagsJSONRequestBody = SaveTagsRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /api/v1/auth/google)
	GoogleAuth(c *gin.Context)

	// (POST /api/v1/auth/logout)
	Logout(c *gin.Context)

	// (GET /api/v1/auth/me)
	Me(c *gin.Context)

	// (POST /api/v1/auth/shops)
	AddShop(c *gin.Context)

	// (PUT /api/v1/auth/shops/{id})
	UpdateShop(c *gin.Context, id Uuid)

	// (PUT /api/v1/auth/tags)
	SaveTags(c *gin.Context)

	// (GET /api/v1/shops)
	ListShops(c *gin.Context)

	// (GET /api/v1/tags)
	ListTags(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// GoogleAuth operation middleware
func (siw *ServerInterfaceWrapper) GoogleAuth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GoogleAuth(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// Me operation middleware
func (siw *ServerInterfaceWrapper) Me(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Me(c)
}

// AddShop operation middleware
func (siw *ServerInterfaceWrapper) AddShop(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.AddShop(c)
}

// UpdateShop operation middleware
func (siw *ServerInterfaceWrapper) UpdateShop(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id Uuid

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateShop(c, id)
}

// SaveTags operation middleware
func (siw *ServerInterfaceWrapper) SaveTags(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SaveTags(c)
}

// ListShops operation middleware
func (siw *ServerInterfaceWrapper) ListShops(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListShops(c)
}

// ListTags operation middleware
func (siw *ServerInterfaceWrapper) ListTags(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListTags(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/auth/google", wrapper.GoogleAuth)
	router.POST(options.BaseURL+"/api/v1/auth/logout", wrapper.Logout)
	router.GET(options.BaseURL+"/api/v1/auth/me", wrapper.Me)
	router.POST(options.BaseURL+"/api/v1/auth/shops", wrapper.AddShop)
	router.PUT(options.BaseURL+"/api/v1/auth/shops/:id", wrapper.UpdateShop)
	router.PUT(options.BaseURL+"/api/v1/auth/tags", wrapper.SaveTags)
	router.GET(options.BaseURL+"/api/v1/shops", wrapper.ListShops)
	router.GET(options.BaseURL+"/api/v1/tags", wrapper.ListTags)
}

type GoogleAuthRequestObject struct {
	Body *GoogleAuthJSONRequestBody
}

type GoogleAuthResponseObject interface {
	VisitGoogleAuthResponse(w http.ResponseWriter) error
}

type GoogleAuth200JSONResponse AuthResponse

func (response GoogleAuth200JSONResponse) VisitGoogleAuthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GoogleAuth400JSONResponse GoogleAuthBadRequestErrorBody

func (response GoogleAuth400JSONResponse) VisitGoogleAuthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GoogleAuth500JSONResponse SessionCreationFailedErrorBody

func (response GoogleAuth500JSONResponse) VisitGoogleAuthResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LogoutRequestObject struct {
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout200Response struct {
}

func (response Logout200Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type Logout400JSONResponse InvalidRequestErrorBody

func (response Logout400JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Logout401JSONResponse AuthenticationRequiredErrorBody

func (response Logout401JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Logout500JSONResponse InternalErrorBody

func (response Logout500JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type MeRequestObject struct {
}

type MeResponseObject interface {
	VisitMeResponse(w http.ResponseWriter) error
}

type Me200JSONResponse User

func (response Me200JSONResponse) VisitMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Me400JSONResponse InvalidRequestErrorBody

func (response Me400JSONResponse) VisitMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type Me401JSONResponse AuthenticationRequiredErrorBody

func (response Me401JSONResponse) VisitMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Me500JSONResponse InternalErrorBody

func (response Me500JSONResponse) VisitMeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type AddShopRequestObject struct {
	Body *AddShopJSONRequestBody
}

type AddShopResponseObject interface {
	VisitAddShopResponse(w http.ResponseWriter) error
}

type AddShop200JSONResponse Shop

func (response AddShop200JSONResponse) VisitAddShopResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type AddShop400JSONResponse AddShopBadRequestErrorBody

func (response AddShop400JSONResponse) VisitAddShopResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type AddShop401JSONResponse AuthenticationRequiredErrorBody

func (response AddShop401JSONResponse) VisitAddShopResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type AddShop403JSONResponse PermissionDeniedErrorBody

func (response AddShop403JSONResponse) VisitAddShopResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type AddShop500JSONResponse InternalErrorBody

func (response AddShop500JSONResponse) VisitAddShopResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateShopRequestObject struct {
	Id   Uuid `json:"id"`
	Body *UpdateShopJSONRequestBody
}

type UpdateShopResponseObject interface {
	VisitUpdateShopResponse(w http.ResponseWriter) error
}

type UpdateShop200Response struct {
}

func (response UpdateShop200Response) VisitUpdateShopResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type UpdateShop400JSONResponse UpdateShopBadRequestErrorBody

func (response UpdateShop400JSONResponse) VisitUpdateShopResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateShop401JSONResponse AuthenticationRequiredErrorBody

func (response UpdateShop401JSONResponse) VisitUpdateShopResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateShop403JSONResponse PermissionDeniedErrorBody

func (response UpdateShop403JSONResponse) VisitUpdateShopResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UpdateShop500JSONResponse InternalErrorBody

func (response UpdateShop500JSONResponse) VisitUpdateShopResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type SaveTagsRequestObject struct {
	Body *SaveTagsJSONRequestBody
}

type SaveTagsResponseObject interface {
	VisitSaveTagsResponse(w http.ResponseWriter) error
}

type SaveTags200JSONResponse TagsResponse

func (response SaveTags200JSONResponse) VisitSaveTagsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type SaveTags400JSONResponse TagBadRequestErrorBody

func (response SaveTags400JSONResponse) VisitSaveTagsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type SaveTags401JSONResponse AuthenticationRequiredErrorBody

func (response SaveTags401JSONResponse) VisitSaveTagsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type SaveTags403JSONResponse PermissionDeniedErrorBody

func (response SaveTags403JSONResponse) VisitSaveTagsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type SaveTags500JSONResponse InternalErrorBody

func (response SaveTags500JSONResponse) VisitSaveTagsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListShopsRequestObject struct {
}

type ListShopsResponseObject interface {
	VisitListShopsResponse(w http.ResponseWriter) error
}

type ListShops200JSONResponse ShopsResponse

func (response ListShops200JSONResponse) VisitListShopsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListShops500JSONResponse InternalErrorBody

func (response ListShops500JSONResponse) VisitListShopsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ListTagsRequestObject struct {
}

type ListTagsResponseObject interface {
	VisitListTagsResponse(w http.ResponseWriter) error
}

type ListTags200JSONResponse TagsResponse

func (response ListTags200JSONResponse) VisitListTagsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ListTags500JSONResponse InternalErrorBody

func (response ListTags500JSONResponse) VisitListTagsResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /api/v1/auth/google)
	GoogleAuth(ctx context.Context, request GoogleAuthRequestObject) (GoogleAuthResponseObject, error)

	// (POST /api/v1/auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)

	// (GET /api/v1/auth/me)
	Me(ctx context.Context, request MeRequestObject) (MeResponseObject, error)

	// (POST /api/v1/auth/shops)
	AddShop(ctx context.Context, request AddShopRequestObject) (AddShopResponseObject, error)

	// (PUT /api/v1/auth/shops/{id})
	UpdateShop(ctx context.Context, request UpdateShopRequestObject) (UpdateShopResponseObject, error)

	// (PUT /api/v1/auth/tags)
	SaveTags(ctx context.Context, request SaveTagsRequestObject) (SaveTagsResponseObject, error)

	// (GET /api/v1/shops)
	ListShops(ctx context.Context, request ListShopsRequestObject) (ListShopsResponseObject, error)

	// (GET /api/v1/tags)
	ListTags(ctx context.Context, request ListTagsRequestObject) (ListTagsResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// GoogleAuth operation middleware
func (sh *strictHandler) GoogleAuth(ctx *gin.Context) {
	var request GoogleAuthRequestObject

	var body GoogleAuthJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GoogleAuth(ctx, request.(GoogleAuthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GoogleAuth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GoogleAuthResponseObject); ok {
		if err := validResponse.VisitGoogleAuthResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx *gin.Context) {
	var request LogoutRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Me operation middleware
func (sh *strictHandler) Me(ctx *gin.Context) {
	var request MeRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Me(ctx, request.(MeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Me")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(MeResponseObject); ok {
		if err := validResponse.VisitMeResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// AddShop operation middleware
func (sh *strictHandler) AddShop(ctx *gin.Context) {
	var request AddShopRequestObject

	var body AddShopJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.AddShop(ctx, request.(AddShopRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "AddShop")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(AddShopResponseObject); ok {
		if err := validResponse.VisitAddShopResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateShop operation middleware
func (sh *strictHandler) UpdateShop(ctx *gin.Context, id Uuid) {
	var request UpdateShopRequestObject

	request.Id = id

	var body UpdateShopJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateShop(ctx, request.(UpdateShopRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateShop")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateShopResponseObject); ok {
		if err := validResponse.VisitUpdateShopResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// SaveTags operation middleware
func (sh *strictHandler) SaveTags(ctx *gin.Context) {
	var request SaveTagsRequestObject

	var body SaveTagsJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SaveTags(ctx, request.(SaveTagsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SaveTags")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(SaveTagsResponseObject); ok {
		if err := validResponse.VisitSaveTagsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListShops operation middleware
func (sh *strictHandler) ListShops(ctx *gin.Context) {
	var request ListShopsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListShops(ctx, request.(ListShopsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListShops")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListShopsResponseObject); ok {
		if err := validResponse.VisitListShopsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTags operation middleware
func (sh *strictHandler) ListTags(ctx *gin.Context) {
	var request ListTagsRequestObject

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListTags(ctx, request.(ListTagsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTags")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ListTagsResponseObject); ok {
		if err := validResponse.VisitListTagsResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}
