databases:
  - name: noodle-map-db
    databaseName: noodle_map
    user: noodle_map_user
    plan: basic-256mb
    region: oregon
    postgresMajorVersion: 18
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere

services:
  - type: web
    name: noodle-map-backend
    runtime: docker
    rootDir: server
    dockerfilePath: ./Dockerfile
    branch: master
    region: oregon
    plan: starter
    autoDeploy: true
    healthCheckPath: /health
    pullRequestPreviewsEnabled: false
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: noodle-map-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: noodle-map-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: noodle-map-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: noodle-map-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: noodle-map-db
          property: database
      - key: DB_SSL_MODE
        value: require
      - key: SERVER_PORT
        value: "80"
      - key: TOKEN_SECRET
        sync: false

  - type: web
    runtime: static
    name: noodle-map-front
    rootDir: web
    buildCommand: npm run build
    staticPublishPath: build/client
    branch: master
    plan: starter
    autoDeploy: true
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_GOOGLE_API_KEY
        sync: false

  - type: cron
    name: backup-db
    runtime: docker
    rootDir: batch/backup-db
    dockerfilePath: ./Dockerfile
    branch: master
    region: oregon
    plan: starter
    schedule: "0 15 * * *"
    autoDeploy: true
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: noodle-map-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: noodle-map-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: noodle-map-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: noodle-map-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: noodle-map-db
          property: database
      - key: DB_SSL_MODE
        value: require
      - key: AWS_REGION
        value: ap-northeast-1
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: S3_BUCKET
        value: noodle-map-bucket
      - key: S3_PREFIX
        value: db-backup
