// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type EatenShop struct {
	ID        uuid.UUID `json:"id"`
	ShopID    uuid.UUID `json:"shopId"`
	Rate      float64   `json:"rate"`
	Favorite  bool      `json:"favorite"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Session struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.UUID      `json:"userId"`
	TokenHash string         `json:"tokenHash"`
	UserAgent sql.NullString `json:"userAgent"`
	CreatedAt time.Time      `json:"createdAt"`
	ExpiresAt time.Time      `json:"expiresAt"`
}

type Shop struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Lat           float64   `json:"lat"`
	Lng           float64   `json:"lng"`
	PostalCode    string    `json:"postalCode"`
	Address       string    `json:"address"`
	GooglePlaceID string    `json:"googlePlaceId"`
	Closed        bool      `json:"closed"`
	CreatedAt     time.Time `json:"createdAt"`
	UpdatedAt     time.Time `json:"updatedAt"`
	Category      string    `json:"category"`
}

type ShopImage struct {
	ID        uuid.UUID `json:"id"`
	ShopID    uuid.UUID `json:"shopId"`
	Path      string    `json:"path"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type ShopsTag struct {
	ID        uuid.UUID `json:"id"`
	ShopID    uuid.UUID `json:"shopId"`
	TagID     string    `json:"tagId"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Tag struct {
	ID        uuid.UUID      `json:"id"`
	Category  sql.NullString `json:"category"`
	Label     string         `json:"label"`
	Slug      string         `json:"slug"`
	Color     string         `json:"color"`
	SortOrder int64          `json:"sortOrder"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
}

type User struct {
	ID        uuid.UUID      `json:"id"`
	Email     string         `json:"email"`
	CreatedAt time.Time      `json:"createdAt"`
	UpdatedAt time.Time      `json:"updatedAt"`
	GoogleSub sql.NullString `json:"googleSub"`
}
