// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: restaurants.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteVisitedRestaurantByRestaurantId = `-- name: DeleteVisitedRestaurantByRestaurantId :exec
delete
from visited_restaurants
where restaurant_id = ?
`

func (q *Queries) DeleteVisitedRestaurantByRestaurantId(ctx context.Context, restaurantID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteVisitedRestaurantByRestaurantId, restaurantID)
	return err
}

const findAllRestaurantCategories = `-- name: FindAllRestaurantCategories :many
select c.id, rc.restaurant_id
from categories c
         inner join restaurants_categories rc on c.id = rc.category_id
`

type FindAllRestaurantCategoriesRow struct {
	ID           uuid.UUID `json:"id"`
	RestaurantID uuid.UUID `json:"restaurantId"`
}

func (q *Queries) FindAllRestaurantCategories(ctx context.Context) ([]FindAllRestaurantCategoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, findAllRestaurantCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAllRestaurantCategoriesRow{}
	for rows.Next() {
		var i FindAllRestaurantCategoriesRow
		if err := rows.Scan(&i.ID, &i.RestaurantID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllRestaurants = `-- name: FindAllRestaurants :many
select r.id,
       r.name,
       r.lat,
       r.lng,
       r.postal_code,
       r.address,
       r.closed,
       r.google_place_id,
       vr.id IS NOT NULL        as visited,
       COALESCE(vr.rate, 0.0)   as rate,
       COALESCE(vr.favorite, 0) as favorite
from restaurants r
         left join visited_restaurants vr on r.id = vr.restaurant_id
`

type FindAllRestaurantsRow struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Lat           float64   `json:"lat"`
	Lng           float64   `json:"lng"`
	PostalCode    string    `json:"postalCode"`
	Address       string    `json:"address"`
	Closed        bool      `json:"closed"`
	GooglePlaceID string    `json:"googlePlaceId"`
	Visited       bool      `json:"visited"`
	Rate          float64   `json:"rate"`
	Favorite      bool      `json:"favorite"`
}

func (q *Queries) FindAllRestaurants(ctx context.Context) ([]FindAllRestaurantsRow, error) {
	rows, err := q.db.QueryContext(ctx, findAllRestaurants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAllRestaurantsRow{}
	for rows.Next() {
		var i FindAllRestaurantsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Lat,
			&i.Lng,
			&i.PostalCode,
			&i.Address,
			&i.Closed,
			&i.GooglePlaceID,
			&i.Visited,
			&i.Rate,
			&i.Favorite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRestaurant = `-- name: InsertRestaurant :exec
insert into restaurants (id, name, lat, lng, postal_code, address, closed, google_place_id)
values (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertRestaurantParams struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Lat           float64   `json:"lat"`
	Lng           float64   `json:"lng"`
	PostalCode    string    `json:"postalCode"`
	Address       string    `json:"address"`
	Closed        bool      `json:"closed"`
	GooglePlaceID string    `json:"googlePlaceId"`
}

func (q *Queries) InsertRestaurant(ctx context.Context, arg InsertRestaurantParams) error {
	_, err := q.db.ExecContext(ctx, insertRestaurant,
		arg.ID,
		arg.Name,
		arg.Lat,
		arg.Lng,
		arg.PostalCode,
		arg.Address,
		arg.Closed,
		arg.GooglePlaceID,
	)
	return err
}

const insertRestaurantCategory = `-- name: InsertRestaurantCategory :exec
insert into restaurants_categories(id, restaurant_id, category_id)
values (?, ?, ?)
`

type InsertRestaurantCategoryParams struct {
	ID           uuid.UUID `json:"id"`
	RestaurantID uuid.UUID `json:"restaurantId"`
	CategoryID   uuid.UUID `json:"categoryId"`
}

func (q *Queries) InsertRestaurantCategory(ctx context.Context, arg InsertRestaurantCategoryParams) error {
	_, err := q.db.ExecContext(ctx, insertRestaurantCategory, arg.ID, arg.RestaurantID, arg.CategoryID)
	return err
}

const updateRestaurant = `-- name: UpdateRestaurant :exec
update restaurants
set name            = ?,
    lat             = ?,
    lng             = ?,
    postal_code     = ?,
    address         = ?,
    closed          = ?,
    google_place_id = ?
where id = ?
`

type UpdateRestaurantParams struct {
	Name          string    `json:"name"`
	Lat           float64   `json:"lat"`
	Lng           float64   `json:"lng"`
	PostalCode    string    `json:"postalCode"`
	Address       string    `json:"address"`
	Closed        bool      `json:"closed"`
	GooglePlaceID string    `json:"googlePlaceId"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) UpdateRestaurant(ctx context.Context, arg UpdateRestaurantParams) error {
	_, err := q.db.ExecContext(ctx, updateRestaurant,
		arg.Name,
		arg.Lat,
		arg.Lng,
		arg.PostalCode,
		arg.Address,
		arg.Closed,
		arg.GooglePlaceID,
		arg.ID,
	)
	return err
}

const upsertVisitedRestaurant = `-- name: UpsertVisitedRestaurant :exec
insert into visited_restaurants(id, restaurant_id, rate, favorite)
values (?, ?, ?, ?)
on conflict(restaurant_id)
    do update set rate     = excluded.rate,
                  favorite = excluded.favorite
`

type UpsertVisitedRestaurantParams struct {
	ID           uuid.UUID `json:"id"`
	RestaurantID uuid.UUID `json:"restaurantId"`
	Rate         float64   `json:"rate"`
	Favorite     bool      `json:"favorite"`
}

func (q *Queries) UpsertVisitedRestaurant(ctx context.Context, arg UpsertVisitedRestaurantParams) error {
	_, err := q.db.ExecContext(ctx, upsertVisitedRestaurant,
		arg.ID,
		arg.RestaurantID,
		arg.Rate,
		arg.Favorite,
	)
	return err
}
