// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
delete
from sessions
where expires_at <= ?1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, now time.Time) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, now)
	return err
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :exec
delete
from sessions
where token_hash = ?
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, deleteSessionByTokenHash, tokenHash)
	return err
}

const extendSession = `-- name: ExtendSession :execrows
update sessions
set expires_at = ?1
where id = ?2
  and expires_at < ?3
`

type ExtendSessionParams struct {
	ExpiresAt   time.Time `json:"expiresAt"`
	ID          uuid.UUID `json:"id"`
	StaleBefore time.Time `json:"staleBefore"`
}

// Conditional extend: only writes (and fsyncs) when the session is stale, i.e.
// when it was last extended before sqlc.arg(stale_before). This keeps the sliding
// window without issuing a row-dirtying write on every authenticated request.
// Returns the number of rows updated so the caller can refresh the cookie at the
// same time it re-persists the session.
func (q *Queries) ExtendSession(ctx context.Context, arg ExtendSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, extendSession, arg.ExpiresAt, arg.ID, arg.StaleBefore)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const findValidSessionByTokenHash = `-- name: FindValidSessionByTokenHash :one
select s.id, u.id as user_id, u.email
from sessions s
         inner join users u on u.id = s.user_id
where s.token_hash = ?1
  and s.expires_at > ?2
`

type FindValidSessionByTokenHashParams struct {
	TokenHash string    `json:"tokenHash"`
	Now       time.Time `json:"now"`
}

type FindValidSessionByTokenHashRow struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"userId"`
	Email  string    `json:"email"`
}

// Compare expires_at against a driver-bound time.Time (sqlc.arg(now)) rather than
// CURRENT_TIMESTAMP so both sides are serialized by the same driver in the same
// format; the comparison stays correct even if the driver's time storage format
// changes.
func (q *Queries) FindValidSessionByTokenHash(ctx context.Context, arg FindValidSessionByTokenHashParams) (FindValidSessionByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, findValidSessionByTokenHash, arg.TokenHash, arg.Now)
	var i FindValidSessionByTokenHashRow
	err := row.Scan(&i.ID, &i.UserID, &i.Email)
	return i, err
}

const insertSession = `-- name: InsertSession :exec
insert into sessions(id, user_id, token_hash, user_agent, expires_at)
values (?, ?, ?, ?, ?)
`

type InsertSessionParams struct {
	ID        uuid.UUID      `json:"id"`
	UserID    uuid.UUID      `json:"userId"`
	TokenHash string         `json:"tokenHash"`
	UserAgent sql.NullString `json:"userAgent"`
	ExpiresAt time.Time      `json:"expiresAt"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	return err
}
