// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: shops.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteEatenShopByShopId = `-- name: DeleteEatenShopByShopId :exec
delete
from eaten_shops
where shop_id = ?
`

func (q *Queries) DeleteEatenShopByShopId(ctx context.Context, shopID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEatenShopByShopId, shopID)
	return err
}

const findAllShops = `-- name: FindAllShops :many
select r.id,
       r.name,
       r.lat,
       r.lng,
       r.postal_code,
       r.address,
       r.closed,
       r.google_place_id,
       r.category,
       vs.id IS NOT NULL        as eaten,
       COALESCE(vs.rate, 0.0)   as rate,
       COALESCE(vs.favorite, 0) as favorite
from shops r
         left join eaten_shops vs on r.id = vs.shop_id
`

type FindAllShopsRow struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Lat           float64   `json:"lat"`
	Lng           float64   `json:"lng"`
	PostalCode    string    `json:"postalCode"`
	Address       string    `json:"address"`
	Closed        bool      `json:"closed"`
	GooglePlaceID string    `json:"googlePlaceId"`
	Category      string    `json:"category"`
	Eaten         bool      `json:"eaten"`
	Rate          float64   `json:"rate"`
	Favorite      bool      `json:"favorite"`
}

func (q *Queries) FindAllShops(ctx context.Context) ([]FindAllShopsRow, error) {
	rows, err := q.db.QueryContext(ctx, findAllShops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAllShopsRow{}
	for rows.Next() {
		var i FindAllShopsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Lat,
			&i.Lng,
			&i.PostalCode,
			&i.Address,
			&i.Closed,
			&i.GooglePlaceID,
			&i.Category,
			&i.Eaten,
			&i.Rate,
			&i.Favorite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertShop = `-- name: InsertShop :exec
insert into shops (id, name, lat, lng, postal_code, address, closed, google_place_id, category)
values (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertShopParams struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Lat           float64   `json:"lat"`
	Lng           float64   `json:"lng"`
	PostalCode    string    `json:"postalCode"`
	Address       string    `json:"address"`
	Closed        bool      `json:"closed"`
	GooglePlaceID string    `json:"googlePlaceId"`
	Category      string    `json:"category"`
}

func (q *Queries) InsertShop(ctx context.Context, arg InsertShopParams) error {
	_, err := q.db.ExecContext(ctx, insertShop,
		arg.ID,
		arg.Name,
		arg.Lat,
		arg.Lng,
		arg.PostalCode,
		arg.Address,
		arg.Closed,
		arg.GooglePlaceID,
		arg.Category,
	)
	return err
}

const updateShop = `-- name: UpdateShop :exec
update shops
set name            = ?,
    lat             = ?,
    lng             = ?,
    postal_code     = ?,
    address         = ?,
    closed          = ?,
    google_place_id = ?,
    category        = ?
where id = ?
`

type UpdateShopParams struct {
	Name          string    `json:"name"`
	Lat           float64   `json:"lat"`
	Lng           float64   `json:"lng"`
	PostalCode    string    `json:"postalCode"`
	Address       string    `json:"address"`
	Closed        bool      `json:"closed"`
	GooglePlaceID string    `json:"googlePlaceId"`
	Category      string    `json:"category"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) UpdateShop(ctx context.Context, arg UpdateShopParams) error {
	_, err := q.db.ExecContext(ctx, updateShop,
		arg.Name,
		arg.Lat,
		arg.Lng,
		arg.PostalCode,
		arg.Address,
		arg.Closed,
		arg.GooglePlaceID,
		arg.Category,
		arg.ID,
	)
	return err
}

const upsertEatenShop = `-- name: UpsertEatenShop :exec
insert into eaten_shops(id, shop_id, rate, favorite)
values (?, ?, ?, ?)
on conflict(shop_id)
    do update set rate     = excluded.rate,
                  favorite = excluded.favorite
`

type UpsertEatenShopParams struct {
	ID       uuid.UUID `json:"id"`
	ShopID   uuid.UUID `json:"shopId"`
	Rate     float64   `json:"rate"`
	Favorite bool      `json:"favorite"`
}

func (q *Queries) UpsertEatenShop(ctx context.Context, arg UpsertEatenShopParams) error {
	_, err := q.db.ExecContext(ctx, upsertEatenShop,
		arg.ID,
		arg.ShopID,
		arg.Rate,
		arg.Favorite,
	)
	return err
}
