// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: shops.sql

package db

import (
	"context"
	"database/sql"
	"strings"

	"github.com/google/uuid"
)

const deleteEatenShopByShopId = `-- name: DeleteEatenShopByShopId :exec
delete
from eaten_shops
where shop_id = ?
`

func (q *Queries) DeleteEatenShopByShopId(ctx context.Context, shopID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteEatenShopByShopId, shopID)
	return err
}

const deleteShopTagsByShopId = `-- name: DeleteShopTagsByShopId :exec
delete
from shops_tags
where shop_id = ?
`

func (q *Queries) DeleteShopTagsByShopId(ctx context.Context, shopID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteShopTagsByShopId, shopID)
	return err
}

const deleteTag = `-- name: DeleteTag :exec
delete
from tags
where id = ?
`

func (q *Queries) DeleteTag(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteTag, id)
	return err
}

const findAllShops = `-- name: FindAllShops :many
select r.id,
       r.name,
       r.lat,
       r.lng,
       r.postal_code,
       r.address,
       r.closed,
       r.google_place_id,
       r.category,
       vs.id IS NOT NULL        as eaten,
       COALESCE(vs.rate, 0.0)   as rate,
       COALESCE(vs.favorite, 0) as favorite
from shops r
         left join eaten_shops vs on r.id = vs.shop_id
`

type FindAllShopsRow struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Lat           float64   `json:"lat"`
	Lng           float64   `json:"lng"`
	PostalCode    string    `json:"postalCode"`
	Address       string    `json:"address"`
	Closed        bool      `json:"closed"`
	GooglePlaceID string    `json:"googlePlaceId"`
	Category      string    `json:"category"`
	Eaten         bool      `json:"eaten"`
	Rate          float64   `json:"rate"`
	Favorite      bool      `json:"favorite"`
}

func (q *Queries) FindAllShops(ctx context.Context) ([]FindAllShopsRow, error) {
	rows, err := q.db.QueryContext(ctx, findAllShops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindAllShopsRow{}
	for rows.Next() {
		var i FindAllShopsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Lat,
			&i.Lng,
			&i.PostalCode,
			&i.Address,
			&i.Closed,
			&i.GooglePlaceID,
			&i.Category,
			&i.Eaten,
			&i.Rate,
			&i.Favorite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findAllTags = `-- name: FindAllTags :many
select id,
       category,
       label,
       slug,
       color,
       sort_order,
       created_at,
       updated_at
from tags
order by sort_order, label
`

func (q *Queries) FindAllTags(ctx context.Context) ([]Tag, error) {
	rows, err := q.db.QueryContext(ctx, findAllTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tag{}
	for rows.Next() {
		var i Tag
		if err := rows.Scan(
			&i.ID,
			&i.Category,
			&i.Label,
			&i.Slug,
			&i.Color,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findTagsByShopIds = `-- name: FindTagsByShopIds :many
select st.shop_id,
       t.id,
       t.category,
       t.label,
       t.slug,
       t.color,
       t.sort_order
from shops_tags st
         join tags t on st.tag_id = t.id
where st.shop_id in (/*SLICE:shop_ids*/?)
order by st.shop_id, t.sort_order, t.label
`

type FindTagsByShopIdsRow struct {
	ShopID    uuid.UUID      `json:"shopId"`
	ID        uuid.UUID      `json:"id"`
	Category  sql.NullString `json:"category"`
	Label     string         `json:"label"`
	Slug      string         `json:"slug"`
	Color     string         `json:"color"`
	SortOrder int64          `json:"sortOrder"`
}

func (q *Queries) FindTagsByShopIds(ctx context.Context, shopIds []uuid.UUID) ([]FindTagsByShopIdsRow, error) {
	query := findTagsByShopIds
	var queryParams []interface{}
	if len(shopIds) > 0 {
		for _, v := range shopIds {
			queryParams = append(queryParams, v)
		}
		query = strings.Replace(query, "/*SLICE:shop_ids*/?", strings.Repeat(",?", len(shopIds))[1:], 1)
	} else {
		query = strings.Replace(query, "/*SLICE:shop_ids*/?", "NULL", 1)
	}
	rows, err := q.db.QueryContext(ctx, query, queryParams...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindTagsByShopIdsRow{}
	for rows.Next() {
		var i FindTagsByShopIdsRow
		if err := rows.Scan(
			&i.ShopID,
			&i.ID,
			&i.Category,
			&i.Label,
			&i.Slug,
			&i.Color,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertShop = `-- name: InsertShop :exec
insert into shops (id, name, lat, lng, postal_code, address, closed, google_place_id, category)
values (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertShopParams struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Lat           float64   `json:"lat"`
	Lng           float64   `json:"lng"`
	PostalCode    string    `json:"postalCode"`
	Address       string    `json:"address"`
	Closed        bool      `json:"closed"`
	GooglePlaceID string    `json:"googlePlaceId"`
	Category      string    `json:"category"`
}

func (q *Queries) InsertShop(ctx context.Context, arg InsertShopParams) error {
	_, err := q.db.ExecContext(ctx, insertShop,
		arg.ID,
		arg.Name,
		arg.Lat,
		arg.Lng,
		arg.PostalCode,
		arg.Address,
		arg.Closed,
		arg.GooglePlaceID,
		arg.Category,
	)
	return err
}

const insertShopTag = `-- name: InsertShopTag :exec
insert into shops_tags (id, shop_id, tag_id)
values (?, ?, ?)
`

type InsertShopTagParams struct {
	ID     uuid.UUID `json:"id"`
	ShopID uuid.UUID `json:"shopId"`
	TagID  string    `json:"tagId"`
}

func (q *Queries) InsertShopTag(ctx context.Context, arg InsertShopTagParams) error {
	_, err := q.db.ExecContext(ctx, insertShopTag, arg.ID, arg.ShopID, arg.TagID)
	return err
}

const insertTag = `-- name: InsertTag :exec
insert into tags (id, category, label, slug, color, sort_order)
values (?, ?, ?, ?, ?, ?)
`

type InsertTagParams struct {
	ID        uuid.UUID      `json:"id"`
	Category  sql.NullString `json:"category"`
	Label     string         `json:"label"`
	Slug      string         `json:"slug"`
	Color     string         `json:"color"`
	SortOrder int64          `json:"sortOrder"`
}

func (q *Queries) InsertTag(ctx context.Context, arg InsertTagParams) error {
	_, err := q.db.ExecContext(ctx, insertTag,
		arg.ID,
		arg.Category,
		arg.Label,
		arg.Slug,
		arg.Color,
		arg.SortOrder,
	)
	return err
}

const updateShop = `-- name: UpdateShop :exec
update shops
set name            = ?,
    lat             = ?,
    lng             = ?,
    postal_code     = ?,
    address         = ?,
    closed          = ?,
    google_place_id = ?,
    category        = ?
where id = ?
`

type UpdateShopParams struct {
	Name          string    `json:"name"`
	Lat           float64   `json:"lat"`
	Lng           float64   `json:"lng"`
	PostalCode    string    `json:"postalCode"`
	Address       string    `json:"address"`
	Closed        bool      `json:"closed"`
	GooglePlaceID string    `json:"googlePlaceId"`
	Category      string    `json:"category"`
	ID            uuid.UUID `json:"id"`
}

func (q *Queries) UpdateShop(ctx context.Context, arg UpdateShopParams) error {
	_, err := q.db.ExecContext(ctx, updateShop,
		arg.Name,
		arg.Lat,
		arg.Lng,
		arg.PostalCode,
		arg.Address,
		arg.Closed,
		arg.GooglePlaceID,
		arg.Category,
		arg.ID,
	)
	return err
}

const updateTag = `-- name: UpdateTag :exec
update tags
set category   = ?,
    label      = ?,
    slug       = ?,
    color      = ?,
    sort_order = ?
where id = ?
`

type UpdateTagParams struct {
	Category  sql.NullString `json:"category"`
	Label     string         `json:"label"`
	Slug      string         `json:"slug"`
	Color     string         `json:"color"`
	SortOrder int64          `json:"sortOrder"`
	ID        uuid.UUID      `json:"id"`
}

func (q *Queries) UpdateTag(ctx context.Context, arg UpdateTagParams) error {
	_, err := q.db.ExecContext(ctx, updateTag,
		arg.Category,
		arg.Label,
		arg.Slug,
		arg.Color,
		arg.SortOrder,
		arg.ID,
	)
	return err
}

const upsertEatenShop = `-- name: UpsertEatenShop :exec
insert into eaten_shops(id, shop_id, rate, favorite)
values (?, ?, ?, ?)
on conflict(shop_id)
    do update set rate     = excluded.rate,
                  favorite = excluded.favorite
`

type UpsertEatenShopParams struct {
	ID       uuid.UUID `json:"id"`
	ShopID   uuid.UUID `json:"shopId"`
	Rate     float64   `json:"rate"`
	Favorite bool      `json:"favorite"`
}

func (q *Queries) UpsertEatenShop(ctx context.Context, arg UpsertEatenShopParams) error {
	_, err := q.db.ExecContext(ctx, upsertEatenShop,
		arg.ID,
		arg.ShopID,
		arg.Rate,
		arg.Favorite,
	)
	return err
}
