// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: users.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const findUserByGoogleSub = `-- name: FindUserByGoogleSub :one
select id, email
from users
where google_sub = ?
`

type FindUserByGoogleSubRow struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

func (q *Queries) FindUserByGoogleSub(ctx context.Context, googleSub sql.NullString) (FindUserByGoogleSubRow, error) {
	row := q.db.QueryRowContext(ctx, findUserByGoogleSub, googleSub)
	var i FindUserByGoogleSubRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const findUserById = `-- name: FindUserById :one
select id, email
from users
where id = ?
`

type FindUserByIdRow struct {
	ID    uuid.UUID `json:"id"`
	Email string    `json:"email"`
}

func (q *Queries) FindUserById(ctx context.Context, id uuid.UUID) (FindUserByIdRow, error) {
	row := q.db.QueryRowContext(ctx, findUserById, id)
	var i FindUserByIdRow
	err := row.Scan(&i.ID, &i.Email)
	return i, err
}

const insertUser = `-- name: InsertUser :exec
insert into users(id, email, google_sub)
values (?, ?, ?)
`

type InsertUserParams struct {
	ID        uuid.UUID      `json:"id"`
	Email     string         `json:"email"`
	GoogleSub sql.NullString `json:"googleSub"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) error {
	_, err := q.db.ExecContext(ctx, insertUser, arg.ID, arg.Email, arg.GoogleSub)
	return err
}
