// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package infrastructure

import (
	"time"

	"github.com/google/uuid"
)

type Restaurant struct {
	ID            uuid.UUID
	Name          string
	Lat           float64
	Lng           float64
	Address       string
	GooglePlaceID string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type TemporaryUser struct {
	ID        uuid.UUID
	Email     string
	Token     string
	CreatedAt time.Time
}

type User struct {
	ID        uuid.UUID
	Email     string
	Password  string
	Salt      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type VisitedRestaurant struct {
	ID           uuid.UUID
	RestaurantID uuid.UUID
	Rate         string
	Favorite     bool
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
